sudo: required
services:
  - docker

before_install:
  - docker build -t ftsanjuan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ftsanjuan/react-test npm test -- --coverage

after_success:
  - docker build -t ftsanjuan/multi-client ./client
  - docker build -t ftsanjuan/multi-nginx ./nginx
  - docker build -t ftsanjuan/multi-server ./server
  - docker build -t ftsanjuan/multi-worker ./worker
  # Log into the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take built images and push them to Docker Hub
  - docker push ftsanjuan/multi-client
  - docker push ftsanjuan/multi-nginx
  - docker push ftsanjuan/multi-server
  - docker push ftsanjuan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  # Must check within S3 for this bucket which is created
  # when you create your Elastic Beanstalk app
  bucket_name: elasticbeanstalk-us-east-1-419786716360
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY